name: computer-vision-models
dependencies:
  - python=3.7
  - tensorflow-gpu==2.2.0
  - pytest
  - matplotlib
  - redis
  - pip
  - pip:
    - tqdm
    - numpy
    - pymongo
    - opencv-python
    - nuscenes-devkit
    - tensorflow-model-optimization
    - redis # to get the python interface for redis
