name: computer-vision-models
dependencies:
  - python=3.8
  - pytest
  - matplotlib
  - redis
  - pip
  - pip:
    - tensorflow-gpu==2.3.1
    - tqdm
    - numpy
    - pymongo
    - opencv-python
    - nuscenes-devkit
    - tensorflow-model-optimization
    - redis # to get the python interface for redis
